### ISSUE TITLE
Data set per session

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-dataset1#2]
We need to finalise the dataset to create exercises for the students.

This should be somehow planned by session. First for protons with increased difficulty, then carbon, dept, etc.

@nes-cgn Can you upload all those dataset and tell us which group of spectra corresponds to which exercise so that we can prepare them and put them online.

**Comment by nes-cgn** [comment]
We can contribute the problems of the month examples, too (currently 15, and one to be added per month in 2020). Also, from our side, there could be without problems some 5-10 more (3 are already there by now). All of them should be also with an NMReDATA assignment, to make it congruent with our project goals.

**Comment by nes-cgn** [comment]
So far, 20 examples. List of molecules and description of difficulty in extra table
